### ISSUE TITLE
[ AVS Private Security ] Generate updated sitemap XML

### ISSUE THREAD

**Issue by holaymolay** [jsdesigns-web-development/frs-static#10]
With the recent changes to the website -- expanded services pages & areas served pages -- the sitemap needs to be updated.

**Comment by zsediqyar** [comment]
Doing some research, I see this to be something manual for us, unlike CMSs that handle it automatically. 

Check this [article](https://www.quora.com/How-can-I-make-a-sitemap-on-a-static-website)

And [THIS](https://www.xml-sitemaps.com) website can generate xml site maps for us
