### ISSUE TITLE
[ AVS Private Security ] add an Articles or Blog section?

### ISSUE THREAD

**Issue by holaymolay** [jsdesigns-web-development/frs-static#11]
For SEO purposes this site could definitely benefit from blog articles. 

The idea here is to create articles like [THIS](https://fastguardservice.com/how-to-choose-a-security-guard-services-company-2018/) that add extra hits to the site. So if someone is doing a search for something like "how to choose a security guard service" then our article will hit on the search results.

My questions is, how will we execute on something like this? Should we create static blog pages or something more dynamic? Let me know your thoughts.

**Comment by zsediqyar** [comment]
This from the beginning was meant to be a static page. If we want to add dynamics to it, then we need to change the whole package name. 
I would vote for a static page.

**Comment by holaymolay** [comment]
actually, I'm just wondering if there's a simple solution that doesn't cost us money.. perhaps some kind of plugin or something? I agree that we should stay static... maybe a static site generator i the solution?

**Comment by zsediqyar** [comment]
The only other solution would be to make a Wordpress page and somehow reroute it to a subdomain in the client's website. 
blog.clientdomain.com or clientdomain.com/blog

but heck, this is too much of work for a flat rate website.
