### ISSUE TITLE
MamaPurni Colors:

### ISSUE THREAD

**Issue by zsediqyar** [jsdesigns-web-development/frs-static#3]
1 - I think the black theme of the template is beautiful, we shouldn't change a lot of it.
2- Let's stick to this convention:

- H2 tags > Saffron
- a tags > pink

We shouldn't use a lot of that BLUE, that sucks! Burns your eyes :'( 

The yellow is bad too, but, better than the BLUE. 

Let me know your idea

**Comment by holaymolay** [comment]
I agree. 

She said she wanted to have a bright website, but she chose a somewhat darker template. So it's up to us to deliver a great-looking website. Brighten it up the best you can, but most importantly all make it look good!
