### ISSUE TITLE
Mama Purnis: Remove Google Map & Add Contact Form

### ISSUE THREAD

**Issue by holaymolay** [jsdesigns-web-development/frs-static#5]
According to [this stackoverflow article](https://stackoverflow.com/a/50977984/3170942), google maps is no longer free. I know it's hard to believe, but that's what they're saying. Because of that, I don't see it being necessary to embed a map into this specific website. 

Instead, we should
1. Remove the map
2. Add a contact form to the right-hand side.
3. Fill-in the background with a color

**Comment by zsediqyar** [comment]
The guy is using the Google Maps through an API call, but, we are embedding it, so it wouldn't cost.

**Comment by holaymolay** [comment]
That's good to know. However, she's a caterer and doesn't have an actual
location. So, the map is superfluous on her site.

**Comment by zsediqyar** [comment]
Done
