### ISSUE TITLE
AVS Private Security: Need to add new section [SEO]

### ISSUE THREAD

**Issue by holaymolay** [jsdesigns-web-development/frs-static#6]
For SEO purposes, I need to create an additional section entitled "Service Areas". 
Under that section, I'll add links to pages for each city in Sonoma County that he services

Cloverdale
Cotati
Healdsburg
Petaluma
Rohnert Park	
Santa Rosa
Sebastopol
Sonoma
Windsor

Each page will be identical except for the name of the city.

Would you please add an additional section below the About Us Section and above the Contact Us Section? If I try doing that myself I think i'll probably break the site 😢

Thanks!!

**Comment by holaymolay** [comment]
Somewhat related, and i'm putting it here because maybe you can kill two birds with one stone. I've noticed that the "what is security?" section and the "Private Security Services" have the same white background.

Perhaps we can alternate each section of the root page Dark-Light-Dark-Light?

**Comment by zsediqyar** [comment]
When did you add it? "What is Security", seems that you broke the design again :man_facepalming: 
lol
The styling is inconsistent with the rest of the page 

I will fix it. 

As for the background color, it is a small div and won't make much sense to color it.

**Comment by zsediqyar** [comment]
I will add the new section under AboutUS

**Comment by zsediqyar** [comment]
Alright, 

I created the section beneath the ABOUT US and also created a template page for CLOVERDALE. If you want to create more pages, just duplicate that page and rename them accordingly. 

If that is good enough and satisfactory, then close this issue :)

**Comment by holaymolay** [comment]
You're the man! Thanks brother for doing it so fast!

**Comment by zsediqyar** [comment]
Te Salude!

**Comment by holaymolay** [comment]
Hey brother, the Contact Us form Labels are now broken after this fix. Any chance of resolving it?
I've looked and don't see what caused it

**Comment by zsediqyar** [comment]
Fixed
